### ISSUE TITLE
Línea del tiempo de la web

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-7-Daniel-Velasco-Lopez#1]
Daniel Velasco López
Línea del tiempo de la web 1.0 - 2.0 - 3.0

![1_20221016_132230_0000](https://user-images.githubusercontent.com/112217987/196051749-ed16e894-8691-4cb4-8112-fd20fa4fe3a4.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 7 "LINEA DEL TIEMPO DE LA WEB"
DE ACUERDO A LA RUBRICA OBTUVISTE ("17.8%") DEL 20% QUE EQUIVALE LA ACTIVIDAD.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
